### ISSUE TITLE
Language fallback inconsistencies

### ISSUE THREAD

**Issue by siebrand** [eloquence/lib.reviews#105]
"nl"/Dutch was just enabled as locale. I went to the registration page, and that looked odd. Makes me think something is wrong in the language fallback code.

Compare:
https://lib.reviews/register?uselang=en (correct)
https://lib.reviews/register?uselang=nl (visible regression "invite link needed" below 'Registreren' haeder)
https://lib.reviews/register?uselang=oc (very bad, "invite link needed" and header about using "uselang" missing)

**Comment by eloquence** [comment]
The third party i18n module unfortunately falls back to the English keys, not messages, when a lookup fails. This will require a PR against upstream to fix.

The reason ?uselang=oc shows English is because oc isn't enabled -- ?uselang just quietly fails in this case. We might want to add a "Language code not recognized" error there.

**Comment by siebrand** [comment]
Fallback to key is big usability issue. That means IMO you should only enable UI languages that are at 100%, and disable them again when you add or outdate strings.

**Comment by keunes** [comment]
> Fallback to key is big usability issue. That means IMO you should only enable UI languages that are at 100%, and disable them again when you add or outdate strings.

I would not disable languages when they're not 100% translated. This could mean a frequent change of language availability which is absulutely undesirable from a user perspective (imagine your default setting change back to English every x weeks).
Moreover, it might be demotivating for translators to have their work disabled much of the time (because of a slight string change in some obscure corner of the website).

If one wants a threshold, I would rather pick 80% or so.

**Comment by eloquence** [comment]
It should now fall back to English when there's no translation -- let me know if you see anything funky.
