### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by regagain** [eloquence/lib.reviews#46]
Good morning / Guten Tag!

Currently reviews can be written in English or in German. What is the plan for supporting more languages?

**Comment by eloquence** [comment]
Hi @regagain  :). We're pretty much ready to add a new language whenever (if it doesn't require additional code -- RTL languages are usually a bit trickier), but I'd like to make sure we have a complete localization for any new languages. I'm going to submit lib.reviews to a localization platform (I'm thinking translatewiki.net, since it has a pretty diverse community thanks to its use by Wikipedia), but before I do that, I want to clean up the i18n files a bit first and add some documentation for translators.

That said, if you want to take a crack at adding a language right now, the format is pretty straightforward. Take a look in locales: https://github.com/eloquence/lib.reviews/tree/master/locales - and feel free to submit a pull request for a new localization file; I'll take care of the rest.

**Comment by keunes** [comment]
+1 for localisations. Just wanted to chip in to say that Transifex also is used by many (F)OSS projects: I'm translating for [AntennaPod](http://antennapod.org/) and find it rather convenient to use (as a translator, as a dev I don't know), a bit more so than translatewiki it seems. Although Transifex is proprietary it's free for open source projects.

**Comment by eloquence** [comment]
Thank you @keunes -- I haven't used it yet but have heard good things about it. Though if we can use a free software platform (and maybe help make it better as part of the experience), I tend to have a preference for that (he said, typing into the GitHub comment form ;-).

**Comment by eloquence** [comment]
FYI, I've just submitted the project for consideration to the translatewiki.net community: https://translatewiki.net/wiki/Thread:Support/Internationalizing_lib.reviews_through_TWN

**Comment by eloquence** [comment]
OK, it took a few patches to get this done, but we're now on translatewiki.net. See this blog post for more details:

https://lib.reviews/team/6bfc0390-e218-4cb7-a446-2046cb886435/post/013b873d-7f3e-4cd5-9d88-ce6c37482c73

Would love your help to get more translations on the way!

**Comment by eloquence** [comment]
And if you want to follow the progress, see:
https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&language=fr&group=lib.reviews

**Comment by keunes** [comment]
@eloquence Gosh, you did choose an overly complex translation tool. Absolutely un-appealing to help translate via that platform. Here, clearly, benefits (FOSS principles) do not outweigh the disadvantages (very bad UX).

**Comment by nemobis** [comment]
Do you have reasons to think that people unaccustomed to both tools find translatewiki.net harder to use? If so, you're encouraged to add suggestions/issues at https://phabricator.wikimedia.org/maniphest/task/create/?projects=MediaWiki-extensions-Translate , ideally after using the software of course.

**Comment by Nikerabbit** [comment]
@keunes Would you like to elaborate what makes you say so? The UX has been defined with a professional UX designer based on user research and testing. I would like to know if you perhaps encountered some bugs or whether there is something we missed to take into account for new users not already familiar with wikis, but have used other translation platforms.

**Comment by keunes** [comment]
> ideally after using the software of course

I cannot even use the software! Absolutely user-unfriendly, and I can tell you: I am used to steep learning curves and often have no problem whatsoever getting accustomed to new platforms.
Why this sucks?
- finding & 'joining' a project's team is not easy-as-in-your-face: when searching on the homepage for "lib.reviews" you get a page with "0 results found". Not particularly a warm welcome. What I would expect here? "Hi, welcome! We found this project here: Lib.reviews. Click on the link to (request to) join the team"
- instead _a bot_ tells me to create my user page - which I cannot b/c I do not have the permission (really?) to do so.
- ... while in turn this is a 'prerequisite' to be able to start translating (why this was set up as a prerequisite is a complete mystery to me; didn't I already indicate the languages I speak on the homepage when creating an account?)
- Nothing happens (except page refresh) when clicking on 'add new request' on https://translatewiki.net/w/i.php?title=Project:Translator&lqt_method=talkpage_new_thread&lqt_subject_field=%7B%7BLanguageHeader%7CYour-ISO-code-here%7D%7D&preload=Project:Translator/preload
- you are prompted - without further explanation - to first translate _random_ strings (one is not familiar with the strings' projects, while knowledge of the app/whatever would always be required to deliver proper translations, and thus this 'test' seems totally pointless)
- the user is not told _how many_ of those random translations are required - I felt like stopping after 15
- the full process of being admitted as a proper translator is [explained](https://translatewiki.net/wiki/Project:Translator) only on a page to which the user has to navigate themselves, whilst I would expect this to be the very first welcome message that pops up after a user created an account.
- I cannot request support ("You cannot post new threads to this discussion page because it has been protected from new threads, or you do not currently have permission to edit.")

> Do you have reasons to think that people unaccustomed to both tools find translatewiki.net harder to use?

@nemobis I'm seriously wondering whether you actually used other platforms - the difference is obvious.

> If so, you're encouraged to add suggestions/issues

I don't feel like creating _yet another_ (Phabricator) account to report a problem on a platform I don't wish to use (Translatewiki)... Sorry.

> The UX has been defined with a professional UX designer based on user research and testing.
Would you like to elaborate what makes you say so?

Well, see above. Can hardly imagine this was developed with a UX expert; in terms of UX especially the very first and second-to-last point are daunting to me. And I'm sorry for the harsh words here; I'm sure good people are working hard to try and make this platform work out, but when unnecessary barriers are raised when you just quickly want to help out a cool initiative this is very frustrating.

**Comment by nemobis** [comment]
So in short you say it is a bit hard to get permission to start (but you 
managed). I can grant this point; it's shared by many free software 
projects. Now I'll go fix some of the points you mentioned. :)

As for the other platforms, sure; we even have a comparison at 
https://docs.google.com/spreadsheets/d/1t6Zo9OmlRCH3N9dOumnWn0w8QrgI9Is2zQXSJB7K-QI/edit 
made with the help of their users.

I also looked into the other translation project you mentioned, and I 
noticed that it's not especially successful, since its peak of 
translation activity is just 1/4 of the peak lib.reviews had on 
translatewiki.net. Feel free to point out any thing that actually goes 
better on other platforms.

**Comment by keunes** [comment]
> So in short you say it is a bit hard to get permission to start (but you managed).

Well, yeah, you could leave out the 'bit' and add 'with much frustration' ;)

> As for the other platforms, sure; we even have a comparison

Ah, I see. A highly technical review - I was talking UX. Which includes design btw; hope that you can do sth about that, too.

> I also looked into the other translation project you mentioned, and I noticed that it's not especially successful, since its peak of translation activity is just 1/4 of the peak lib.reviews had on translatewiki.net.

Which project are we talking about here? Transifex in general, or AntennaPod specifically? If the latter: 13 languages have had a full 100% translation for a while already (plus 5 over 70%) and there hasn't been an update to the app for a while, so little recent activity could be expected. Plus the project doesn't have the attraction that newly launched projects have. So if you indeed are referring to AntennaPod - that's not really a fair comparison.

> Feel free to point out any thing that actually goes better on other platforms.

Some other things, apart from the rage posted above:
- the mess with the 'forum'. I just created a message asking for further clarification on a specific string and it does not appear (not even a notification) next to the string. So I don't know if anyone gets a message about my request for further info (which I would hope otherwise it's just hanging in space), but I do know I don't get feedback on my action (I'm talking UI feedback here, not from actual ppl). Language questions get mixed up with process questions ('meta questions' so to say, including on the functioning of the platform). I can only refer to Transifex where the 'managers' (aka developers) get a notifaction when I post a question, and I get a notification when they reply - in the translation interface so that I can immediately act upon the new info.
- There is no visual distinction between translated and proofread strings on [this page](https://translatewiki.net/w/i.php?title=Special:Translate&group=lib.reviews&action=translate&language=nl&filter=) nor is there in the statistics.
- The whole 'messaging group' concept is unclear to me. Isn't that basically what one would call a 'project'?
- There's no easy way to navigate within a 'project space'. I would expect four big buttons on every project page: Project info (now: [Translating:](https://translatewiki.net/wiki/Translating:Lib.reviews)), Translate (now: [Special:Translate](https://translatewiki.net/w/i.php?title=Special:Translate&group=lib.reviews&language=en-gb&filter=%21translated&action=translate)), Languages (now: [Special:MessageGroupStats](https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&group=lib.reviews)), Support (doesn't exist).

**Comment by keunes** [comment]
@nemobis Thanks for following up btw :)
@eloquence sorry for mis-using your github space :/

**Comment by eloquence** [comment]
@keunes No need to apologize, thanks for sharing your experience & frustrations and starting on the Dutch translation in spite of the latter. It looks like you're able to post to https://translatewiki.net/wiki/Support now? If so we may want to move TWN specific issues there so the community has a chance to weigh in / help file appropriate bugs.

FYI, beyond the free software concern, a big reason I picked TWN as a platform is primarily that there's a pretty active community there that's often happy to jump in to help translate projects they don't necessarily use themselves. Because it's still early days for lib.reviews, there have been only a few folks from our community (Dimi, Pizzaiolo, myself and yourself) who've been able to help with translations so far. But we've already reached 10 translations with 100% (some of which will go live with the next update) thanks in large part to the TWN community.

That said, I think everyone recognizes that it can be tricky to get started. The platform has gotten a little bit of help from the Wikimedia Foundation, but nowadays most people working on it are either volunteers or have to squeeze it in alongside a lot of other stuff they're working on. Once you're in the door, it can be a lot of fun to use (hence the committed volunteers), in spite of its quirks.

The "Alt+Shift+S" access-key issue, BTW, is just how that feature of HTML works -- the browser/OS picks the modifier key(s). MediaWiki even has some custom code to try to show the correct keyboard combination for each platform. In the case of Alt+Shift+S, note that you can use Alt+S if you're using a Chrome/Chromium based browser on Windows or Linux. But for other keyboard combinations like Alt+D or Alt+F, you need to use Shift even in Chrome, which is why the help text is identical on Firefox and Chrome.

I've filed #86 to investigate Weblate as an *additional* tool to support, since it's open source and a bit simpler to use (while lacking some features). We might be able to support one or more alternatives for specific language(s). But in the meantime, if TWN does work for you now that you've got a foot in the door, it's best to continue the translation there, and to use https://translatewiki.net/wiki/Support and #mediawiki-i18n for any issues that come up (I pay attention to both of those venues, as well).

**Comment by fitojb** [comment]
As a translator who has used many l10n platforms, among them Transifex, Pootle, Crowdin, Launchpad and Weblate, I completely disagree that Translatewiki.net is unusable. Just IMHO…

**Comment by keunes** [comment]
> It looks like you're able to post to https://translatewiki.net/wiki/Support now? If so we may want to move TWN specific issues there so the community has a chance to weigh in / help file appropriate bugs.

Good idea. Did it.

> a big reason I picked TWN as a platform is primarily that there's a pretty active community there that's often happy to jump in to help translate projects they don't necessarily use themselves.

Didn't know, that indeed is a big advantage

> The "Alt+Shift+S" access-key issue, BTW, is just how that feature of HTML works

To be honest, as an end-user I don't *care* how HTML works (or not). I simply want a good experience (now, don't get me wrong, I do appreciate your explanation). But in Transifex I just press TAB to save & go to the next string (at least in Firefox) - don't know how they did it, but it's very convenient. :)

> We might be able to support one or more alternatives for specific language(s). But in the meantime, if TWN does work for you now that you've got a foot in the door, it's best to continue the translation there

Yeah, if I were a project maintainer I would want to avoid using multiple platforms for translation ^^ Indeed, now that it works I'll just use TWN and hope the volunteers will manage to improve its UI/X.

> As a translator who has used many l10n platforms, among them Transifex, Pootle, Crowdin, Launchpad and Weblate, I completely disagree that Translatewiki.net is unusable. Just IMHO… (@fitojb)

Well, I never said it's unusable. When you actually get to use it, it's pretty ok. But my complaints - if read carefully - started off with _being unable_ to use the platform. And once annoyed, you start to complain about every little detail (at least, that's how I work ^^). I only have experience with Transifex (and a bit of Crowdin - which is pretty similar) and I really prefer Transifex over TWN (mainly because of it's design and in-context feedback system which is lacking in TWN), but maybe compared to Launchpad and other platforms TWN is like heaven :)

**Comment by TheLastProject** [comment]
It may be relevant to mention that F-Droid migrated from TranslateWiki to Weblate, which is still Free Software, Kontalk migrated from Transifex to Weblate and AsteroidOS started off with Weblate. All of them seem very positive about Weblate, and in my experience it's much more user-friendly than TranslateWiki.

**Comment by siebrand** [comment]
> It may be relevant to mention that F-Droid migrated from TranslateWiki to Weblate

Maybe a bit off-topic here, but F-Droid hasn't ever been up for translation on translatewiki.net, so this statement is incorrect.

**Comment by nemobis** [comment]
Siebrand Mazeland, 04/11/2016 22:16:
> Maybe a bit off-topic here, but F-Droid hasn't ever been up for
> translation on translatewiki.net, so this statement is incorrect.

Yeah, I wanted to say the same. They used to have their own MediaWiki 
Translate installation at https://f-droid.org/translate/ , but I don't 
know how it was configured. From 
https://f-droid.org/forums/topic/new-translation-system/#post-9595 it 
looks like they were not using all Translate features (since most of 
what they describe as lacking is actually offered by translatewiki.net).

**Comment by eloquence** [comment]
Since we have support for 16 languages now, I'm marking this closed; other language-related issues should be logged separately.
