### ISSUE TITLE
Get adopted by Wikimedia

### ISSUE THREAD

**Issue by pizzamaker** [eloquence/lib.reviews#50]
Think about it. This project has everything to do with the Wikimedia family, and full integration with it would be very benefitial to both.

Wikivoyage, if I recall correctly, was adopted by Wikimedia upon request. Maybe that would be a good option for lib.reviews as well.

**Comment by eloquence** [comment]
Unfortunately, the project would likely be considered out of scope, since it is neither educational nor wiki-based:
https://meta.wikimedia.org/wiki/Mission

I've been focusing instead on re-cultivating http://wiki.freeculture.org/Main_Page as an incubation space for free culture projects and activities.

That said, I definitely want to make sure there are strong bridges to relevant free culture projects including Wikimedia and OpenStreetMap, and have reached out to the Wikivoyage and OSM communities.
