### ISSUE TITLE
Investigate Weblate as (additional) TWN alternative for translation

### ISSUE THREAD

**Issue by eloquence** [eloquence/lib.reviews#86]
Some users have problems using translatewiki.net . It would be nice to _also_ support https://weblate.org/ for translators who prefer it, but we'd ideally want to whitelist the specific languages we use it for.

**Comment by siebrand** [comment]
translatewiki.net allows blacklisting languages. In our experience, using multiple platforms for the same languages is a bad idea, and to be advised against, or possibly a blocker for twn support. Ping @Nikerabbit.

**Comment by keunes** [comment]
Actually, I would now support this, at least for Dutch. Despite the starting problems I had started with TWN, but random people started to change my input (first without explanation, then giving stupid arguments if asked) without being actually useful (meaning: not providing new translations). So I quickly lost interest.

I'd be willing to restart translation works on weblate.

**Comment by siebrand** [comment]
> not providing new translations

Can you please point me to an example of this? Thanks.

**Comment by nemobis** [comment]
> people started to change my input

Apparently this is about [one edit](https://translatewiki.net/w/i.php?title=lib.reviews:sign_in/nl&diff=prev&oldid=7098427) out of ~350 translations that Siebrand made and a dozen by Keunes (most of which [are unaltered](https://translatewiki.net/wiki/Special:Contributions/Keunes)).

Collaboration brings improvement: the solution to misunderstanding and disagreements is to open a discussion, not to give someone more power over others. As far as I can tell, no discussion was attempted here.

If the project has some specific glossary or style rules or whatever, of course, those can be added to the [project page](https://translatewiki.net/wiki/Translating:Lib.reviews) so that translators know.

**Comment by eloquence** [comment]
There doesn't appear to be much demand for this in practice now that we're fully up and running on TWN; closing for the time being.
