### ISSUE TITLE
human readable slugs

### ISSUE THREAD

**Issue by tjgillies** [eloquence/lib.reviews#97]
@eloquence you said you had an idea of how you would do it. Mind outlining that flow?

**Comment by eloquence** [comment]
Here's how I'd suggest going about it:

- Let's start with "things" (review subjects), then "teams" and then maybe individual reviews/blog posts/etc..
- A slug is optional. When it is present, the URL will only use the slug and URLs with GUIDs will redirect to it. When it is not, it will use the GUID. 
- A slug should be considered highly stable (it may break, but we will attempt to retain aliases).
- We will still expose the GUID as an alternative link for users who want to ensure that their link never breaks unless the resource is deleted.

So you could have a slug like lib.reviews/papa-gees which would be the same as thing/1b3c18a2-576b-4194-88e8-eca8e8476cf9 , and the latter would redirect to the former. If papa-gees is renamed, we would keep it as an alias. We may want to limit the total number of aliases to 3-5 to keep the namespace clean.

In terms of implementation, since RethinkDB only supports one unique primary key per table, we will likely need separate tables for thing-slugs, team-slugs, etc.

In terms of UI, we would initially put the thing-slugs on the thing page, where we have the "Add a label" button.

This design has drawbacks, but I personally prefer it to a "GUID + arbitrary string" scheme because it leads to very clean, _memorable_ URLs, which is important e.g. for software maintainers, business owners, etc. Note that other review sites like Yelp use a similar scheme (except for the total absence of GUIDs).

**Comment by eloquence** [comment]
We'd enforce certain character restrictions on slugs. At the very least, to avoid any kind of case conflict issues, scripts with case sensitivity would be lower-cased, and common separators like underscores and spaces would be normalized to hyphens.

**Comment by eloquence** [comment]
Done for teams; "things" are next.

**Comment by eloquence** [comment]
This has been done for a while; we're not planning to add slugs for individual blog posts or reviews at this time, so closing for now.
